### ISSUE TITLE
configSearchPaths setting is not respected

### ISSUE THREAD

**Issue by doroshenko** [vknabel/vscode-swiftlint#8]
The extension seems to be always using the default SwiftLint ruleset and ignores the specified custom search path.

I have `.swiftlint.yml` file placed in my home directory and `~/.swiftlint.yml` is added to "Config Search Paths" setting. 

When I open a swift file in VSCode it is linted using the standard rules and not the ones in the config file.
Manually running `swiftlint lint --config ~/.swiftlint.yml test.swift` performs linting using custom rules as expected.

**Comment by vknabel** [comment]
Thanks for your report. The extension didn't handle absolute and `~` paths correctly.
Version [1.0.5](https://github.com/vknabel/vscode-swiftlint/releases/tag/1.0.5) includes a fix.

**Comment by vknabel** [comment]
I also released updates for other extensions which had the same bug [vknabel/vscode-swiftformat@1.3.5](https://github.com/vknabel/vscode-swiftformat/releases/tag/1.3.5) and [vknabel/vscode-apple-swift-format@1.0.2](https://github.com/vknabel/vscode-apple-swift-format/releases/tag/1.0.2)

**Comment by doroshenko** [comment]
Thanks for your swift reply, but I still cannot make the extension recognize a custom `.swiftlint.yml` file neither with a relative, nor with an absolute path even after updating to 1.0.5. It's always using the default rules for me. 
 
I'm running macOS Catalina 10.15.3.

**Comment by vknabel** [comment]
Hey @doroshenko!

Sorry for the delay. I have to admit, that I forgot to deeper look at this issue.
It seemed the previous fix did only work for the initial linting of the whole workspace, but not for single files. This is fixed in [1.1.0](https://github.com/vknabel/vscode-swiftlint/releases/tag/1.1.0).

**Comment by doroshenko** [comment]
Everything's working correctly now. Thank you!
